name: Devkit Power On

on:
  pull_request:
    branches: ['main']
    paths:
      - '.github/workflows/devkit-power-on.yml'

jobs:
  power-on:
    name: Power on devkit
    runs-on: [self-hosted, playstation, windows, x64, vie]
    timeout-minutes: 10

    steps:
      - run: prospero-ctrl power on
