name: Prepare Release
permissions: read-all

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (semver, "major"/"minor"/"patch", or leave empty for auto)'
        required: false
      force:
        description: 'Force release even with blockers'
        type: boolean
        default: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_RELEASE_PAT }}
      - uses: getsentry/craft@v2
        with:
          version: ${{ inputs.version }}
          force: ${{ inputs.force }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
