name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (or "auto")
        required: false
      force:
        description: Force a release even when there are release-blockers
        type: boolean
        default: false

permissions: read-all

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_RELEASE_PAT }}
      - uses: getsentry/craft@v2
        with:
          version: ${{ inputs.version }}
          force: ${{ inputs.force }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
